In [1]:
import seaborn as sns
import scipy.stats as stats
from statsmodels.stats import weightstats
import numpy as np
import pandas as pd
import random
import warnings
import matplotlib.pyplot as plt
%matplotlib inline


In [2]:
df = pd.read_csv('https://query.data.world/s/32tfmhwuq4vtfda5ykqixlqnixj2jx')

In [3]:
data = pd.DataFrame(df)

In [4]:
data.head()

PEOPLE_POSITIVE_CASES_COUNT COUNTY_NAME PROVINCE_STATE_NAME REPORT_DATE  \
0                            0      Greene             Alabama  2020-01-21   
1                            0      Greene             Alabama  2020-01-22   
2                            0      Greene             Alabama  2020-01-23   
3                            0      Greene             Alabama  2020-01-24   
4                            0      Greene             Alabama  2020-01-25   

  CONTINENT_NAME DATA_SOURCE_NAME  PEOPLE_DEATH_NEW_COUNT  COUNTY_FIPS_NUMBER  \
0        America   New York Times                       0              1063.0   
1        America   New York Times                       0              1063.0   
2        America   New York Times                       0              1063.0   
3        America   New York Times                       0              1063.0   
4        America   New York Times                       0              1063.0   

  COUNTRY_ALPHA_3_CODE COUNTRY_SHORT_NAME COUNTRY_ALPHA_2_CODE  \
0                  USA      United States                   US   
1                  USA      United States                   US   
2                  USA      United States                   US   
3                  USA      United States                   US   
4                  USA      United States                   US   

   PEOPLE_POSITIVE_NEW_CASES_COUNT  PEOPLE_DEATH_COUNT  
0                                0                   0  
1                                0                   0  
2                                0                   0  
3                                0                   0  
4                                0                   0

In [5]:
data = data.drop(['COUNTY_NAME','PROVINCE_STATE_NAME'], axis=1)

In [6]:
data.head()

PEOPLE_POSITIVE_CASES_COUNT REPORT_DATE CONTINENT_NAME DATA_SOURCE_NAME  \
0                            0  2020-01-21        America   New York Times   
1                            0  2020-01-22        America   New York Times   
2                            0  2020-01-23        America   New York Times   
3                            0  2020-01-24        America   New York Times   
4                            0  2020-01-25        America   New York Times   

   PEOPLE_DEATH_NEW_COUNT  COUNTY_FIPS_NUMBER COUNTRY_ALPHA_3_CODE  \
0                       0              1063.0                  USA   
1                       0              1063.0                  USA   
2                       0              1063.0                  USA   
3                       0              1063.0                  USA   
4                       0              1063.0                  USA   

  COUNTRY_SHORT_NAME COUNTRY_ALPHA_2_CODE  PEOPLE_POSITIVE_NEW_CASES_COUNT  \
0      United States                   US                                0   
1      United States                   US                                0   
2      United States                   US                                0   
3      United States                   US                                0   
4      United States                   US                                0   

   PEOPLE_DEATH_COUNT  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0

In [7]:
data = data.drop(['DATA_SOURCE_NAME','PEOPLE_DEATH_NEW_COUNT','COUNTY_FIPS_NUMBER','COUNTRY_ALPHA_3_CODE'], axis=1)

In [8]:
data = data.drop(['COUNTRY_ALPHA_2_CODE','PEOPLE_POSITIVE_NEW_CASES_COUNT', 'REPORT_DATE'],axis=1)

In [9]:
data.head()

PEOPLE_POSITIVE_CASES_COUNT CONTINENT_NAME COUNTRY_SHORT_NAME  \
0                            0        America      United States   
1                            0        America      United States   
2                            0        America      United States   
3                            0        America      United States   
4                            0        America      United States   

   PEOPLE_DEATH_COUNT  
0                   0  
1                   0  
2                   0  
3                   0  
4                   0

In [10]:
data.CONTINENT_NAME.unique()

array(['America', 'Oceania', 'Europe', 'Asia', 'Africa', nan],
      dtype=object)

In [11]:
data1 = data.loc[data['CONTINENT_NAME']=='Oceania']
data2 = data.loc[data['CONTINENT_NAME']=='Asia']
d = data.loc[data['CONTINENT_NAME']=='Europe']
data2 = data2.append(d)
data3 = data.loc[data['CONTINENT_NAME']=='America']

In [12]:
d = data1.groupby('COUNTRY_SHORT_NAME')
d2 = data2.groupby('COUNTRY_SHORT_NAME')
d3 = data3.groupby('COUNTRY_SHORT_NAME')

In [13]:
d.head()

PEOPLE_POSITIVE_CASES_COUNT CONTINENT_NAME COUNTRY_SHORT_NAME  \
1151256                            0        Oceania    Solomon Islands   
1151257                            0        Oceania    Solomon Islands   
1151258                            0        Oceania    Solomon Islands   
1151259                            0        Oceania    Solomon Islands   
1151260                           17        Oceania    Solomon Islands   
1172151                          611        Oceania          Australia   
1172152                          609        Oceania          Australia   
1172153                          608        Oceania          Australia   
1172154                          658        Oceania          Australia   
1172155                          868        Oceania          Australia   
1173297                            0        Oceania              Samoa   
1173298                            0        Oceania              Samoa   
1173299                            0        Oceania              Samoa   
1173300                            0        Oceania              Samoa   
1173301                            2        Oceania              Samoa   
1174061                            0        Oceania   Marshall Islands   
1174062                            0        Oceania   Marshall Islands   
1174063                            0        Oceania   Marshall Islands   
1174064                            0        Oceania   Marshall Islands   
1174065                            4        Oceania   Marshall Islands   
1214513                           21        Oceania      New Caledonia   
1214514                           21        Oceania      New Caledonia   
1214515                           21        Oceania      New Caledonia   
1214516                           22        Oceania      New Caledonia   
1214517                           40        Oceania      New Caledonia   
1240676                            0        Oceania   Papua New Guinea   
1282203                           62        Oceania   French Polynesia   
1282204                           62        Oceania   French Polynesia   
1282205                           60        Oceania   French Polynesia   
1282206                           62        Oceania   French Polynesia   
1282207                        16926        Oceania   French Polynesia   
1285356                           18        Oceania               Fiji   
1285357                           18        Oceania               Fiji   
1285358                           18        Oceania               Fiji   
1285359                           27        Oceania               Fiji   
1285360                           49        Oceania               Fiji   
1300654                           11        Oceania   Papua New Guinea   
1300655                           11        Oceania   Papua New Guinea   
1300656                           10        Oceania   Papua New Guinea   
1300657                           39        Oceania   Papua New Guinea   
1318247                            0        Oceania            Vanuatu   
1352227                         1530        Oceania        New Zealand   
1352228                         1528        Oceania        New Zealand   
1352229                         1519        Oceania        New Zealand   
1352230                         1556        Oceania        New Zealand   
1352231                         2181        Oceania        New Zealand   
1354444                            0        Oceania            Vanuatu   
1354445                            0        Oceania            Vanuatu   
1354446                            0        Oceania            Vanuatu   
1354447                            0        Oceania            Vanuatu   

         PEOPLE_DEATH_COUNT  
1151256                   0  
1151257                   0  
1151258                   0  
1151259                   0  
1151260                   0  
1172151                   9  
1172152                 

In [14]:
mean1 = d.mean()
mean2 = d2.mean()
mean3 = d3.mean()

In [15]:
mean_total = mean1.append(mean2)

In [16]:
mean_total = mean_total.append(mean3)

In [17]:
mean_total

PEOPLE_POSITIVE_CASES_COUNT  PEOPLE_DEATH_COUNT
COUNTRY_SHORT_NAME                                                       
Australia                                 2008.246410           54.365862
Fiji                                        25.177546            0.926893
French Polynesia                          4375.070496           25.827676
Marshall Islands                             0.929504            0.000000
New Caledonia                               22.130548            0.000000
...                                               ...                 ...
Trinidad and Tobago                       2531.736292           46.859008
Turks and Caicos Islands                   375.078329            3.086162
United States                             2087.181150           48.923495
Uruguay                                   5179.297650           64.263708
Venezuela                                43819.718016          386.297650

[159 rows x 2 columns]

In [18]:
mean = mean_total.mean()
std = mean_total.std()

In [19]:
print("mean: ", mean)
print("standard deviation: ", std)

mean:  PEOPLE_POSITIVE_CASES_COUNT    132059.108369
PEOPLE_DEATH_COUNT               3668.535432
dtype: float64
standard deviation:  PEOPLE_POSITIVE_CASES_COUNT    423428.285307
PEOPLE_DEATH_COUNT              11125.811714
dtype: float64


In [20]:
mean_total.head()

PEOPLE_POSITIVE_CASES_COUNT  PEOPLE_DEATH_COUNT
COUNTRY_SHORT_NAME                                                 
Australia                           2008.246410           54.365862
Fiji                                  25.177546            0.926893
French Polynesia                    4375.070496           25.827676
Marshall Islands                       0.929504            0.000000
New Caledonia                         22.130548            0.000000

In [21]:
contingency_table=pd.crosstab(mean_total['PEOPLE_POSITIVE_CASES_COUNT'],mean_total["PEOPLE_DEATH_COUNT"])
print('contingency_table :-\n',contingency_table)


contingency_table :-
 PEOPLE_DEATH_COUNT           0.000000      0.078329      0.083551      \
PEOPLE_POSITIVE_CASES_COUNT                                             
2.323760e-01                            1             0             0   
3.994778e-01                            1             0             0   
9.295039e-01                            1             0             0   
4.245431e+00                            1             0             0   
4.441253e+00                            1             0             0   
...                                   ...           ...           ...   
7.785232e+05                            0             0             0   
8.146599e+05                            0             0             0   
1.111557e+06                            0             0             0   
3.154584e+06                            0             0             0   
3.853645e+06                            0             0             0   

PEOPLE_DEATH_COUNT          

In [22]:
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 1 0]]


In [23]:
b=stats.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)

Expected Values :-
 [[0.09433962 0.00628931 0.00628931 ... 0.00628931 0.00628931 0.00628931]
 [0.09433962 0.00628931 0.00628931 ... 0.00628931 0.00628931 0.00628931]
 [0.09433962 0.00628931 0.00628931 ... 0.00628931 0.00628931 0.00628931]
 ...
 [0.09433962 0.00628931 0.00628931 ... 0.00628931 0.00628931 0.00628931]
 [0.09433962 0.00628931 0.00628931 ... 0.00628931 0.00628931 0.00628931]
 [0.09433962 0.00628931 0.00628931 ... 0.00628931 0.00628931 0.00628931]]


In [24]:
no_of_rows=len(contingency_table.iloc[0:2,0])
no_of_columns=len(contingency_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:",ddof)

Degree of Freedom: 1


In [25]:
alpha = 0.05
from scipy.stats import chi2

In [26]:
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:",chi_square_statistic)

chi-square statistic: 301.99999999999955


In [27]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [28]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)

p-value: 0.0
Significance level:  0.05
Degree of Freedom:  1
chi-square statistic: 301.99999999999955
critical_value: 3.841458820694124
p-value: 0.0


In [29]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Retain H0,There is no relationship between 2 categorical variables")

Reject H0,There is a relationship between 2 categorical variables
Reject H0,There is a relationship between 2 categorical variables
